config/routes.rb
Tutorme::Application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  root to: 'static_pages#home'

  resources :profiles

end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
	
	belongs_to  :user
	has_many :educations 
	has_many :subjects


	def name
		"#{first_name} #{last_name}"
	end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :profile
end

app/models/user.rb
class User < ActiveRecord::Base

	has_one :profile
	accepts_nested_attributes_for :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def with_profile
  	self.profile.build
  	self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) << :profile_attributes
  # end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def index
		@profiles = Profile.all
	end	

	def show
		@profile = Profile.find(params[:id])
	end

	def new 

	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    def create
      

		#uploader.retrieve_from_store!('my_file.png')
		    
		flash[:error] = "Post successfully created"

		uploader = AvatarUploader.new
		uploader.store!(params[:avatar])

		puts params[:avatar]

		#redirect_to "/users/sign_up"

		super		
    end


  private

    def sign_up_params
      params.require(resource_name).permit(:email, :password, :password_confirmation, profile_attributes: [:first_name, :last_name, :avatar])
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutorme</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
</head>
<body>
	<div id="header">
		<%= image_tag('leaf.png', class: 'logo') %>
		<h1>Tutor Me</h1>
		<ul>
			<% if user_signed_in? %>
				<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
			<% else %>
				<li><%= link_to "Sign in", new_user_session_path %></li>
			<% end %>
		</ul>
	</div>

	<div id="navigation">
		<ul id="nav">
			<li><%= link_to "Home", root_url, id: request.url == root_url ? 'current' : '' %></li>
			<li><%= link_to "Browse Tutors", profiles_path, id: request.url == profiles_url ? 'current': '' %>
			<li><%= link_to "Become A Tutor", new_user_registration_path, id: request.url == new_user_registration_url ? 'current' : '' %></li>
		</ul>
	</div>
		
			<%= yield %>


</body>
</html>

app/views/profiles/show.html.erb
<h1><%= @profile.name %></h1>
<p><%= @profile.bio %></p>
<h2>Education</h2>

	<% @profile.educations.each do |education| %>
		<ul>
			<li>School: <%= education.school %></li>
			<li>Degree: <%= education.degree %></li>
			<li>Major/Specialization: <%= education.specialization %></li>
		</ul>
	<% end %>

<h2>Subjects</h2>
	
	<% @profile.subjects.each do |subject| %>
		<ul>
			<li><%= subject.name %></li>
			<li><%= subject.level %></li>
		</ul>
	<% end %>

<%= link_to "Back", profiles_path %>

app/views/static_pages/home.html.erb
<div id="home">
	<div id="alpha_wrapper">
		<div id="alpha_2">
		</div>
		<div id="text_holder_2">
			<h1 >Find your perfect tutor</h1>
				<h2>Get instant Help</h2>
				<%= link_to "Find A Tutor", profiles_path, class: 'hero-button-link', id: 'hero' %>
		</div>
	</div>
</div>